secret_vars:
    AWS_IAM_ACCOUNT: ENC[AES256_GCM,data:GlR7VZhobOW9FlY=,iv:EovVhAwhuXnSeDQM8t8DPuSoiZtMTtzA4W0f+M/Yx/U=,tag:97LtFyAXUeMjJTENZ8iRjQ==,type:str]
    AWS_ACCESS_KEY: ENC[AES256_GCM,data:VrJLsF8KoGkOmOh4halFl9XggNs=,iv:wTRgC7MA3FzgscI4J7k4J1DR2XuY29SVXOyJFjcsMUs=,tag:iOrg8qRxI9+XH0RC9vNWyg==,type:str]
    AWS_SECRET_KEY: ENC[AES256_GCM,data:wt893uK/LKd/CfS/kAtV35BV0GMW0qZxc8izfxpgNMKXLwA8NqJW/Q==,iv:TzJvUHKO2XvkrcIQG7wQMIk9CwjGy7skkNjn4fVRMNA=,tag:mgLl15/6KAgsw81LIMuN0w==,type:str]
    API_KEY_NAME: ENC[AES256_GCM,data:Raa9LHQ+rA==,iv:nllGq1/88XSdIKr4wOZNF1YUZJzPzNzYfnDZ5QWA4gs=,tag:Vrp0krvfXTf+xhTc3Av1DA==,type:str]
    API_KEY: ENC[AES256_GCM,data:2FiKEddIr7HH493DmnQWAPm/wDCMAT6cY3F2BmcfBg==,iv:cjazSNMaFsSiBpMl/DKCQ1sbHXbTZrIy7EFWISSj4Ck=,tag:h6SJ4DYBeULeAuxxHaD+Xg==,type:str]
    ENVIRONMENT: ENC[AES256_GCM,data:Cl5Z59Zipg==,iv:OpXu80gnUUZrw4+KQjOqXl2EkM9fRnOOksB8qfiVkKU=,tag:nB28HDa3jpBvm7/nV7N3kg==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:CsHvTYwqnViQQ+1x0WbTMIWc6DlM4NKkws0A5QEvCXEQoQ3uGsNCDa687gdA17CzNT6HukoKEpLXnxilqm8N9ec3bUzQcSKd,iv:KE3KkoBizRyu8QMbYs7NIzS+qMm8HSkzbE9NKoQ6cFw=,tag:5U8G/QaclJ4jbO9OWjYdyw==,type:str]
    SENTRY_TRACE_SAMPLE_RATE: ENC[AES256_GCM,data:sJfU,iv:EqSKUpcYPATrq1mp6R+PArfpFOj7CHB2PKhhrsl64Yk=,tag:LSFbXAvdQo9xQO3bS5ah8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-06-01T15:02:18Z'
    mac: ENC[AES256_GCM,data:1tCjY+Gt8rzGoOUvG+4huVNwaU6hmW4rVdRv8GtJSDWV8Ur9TEOUuxrTAWuQAsrrnmgPGDFtXYM/+qnq9W2T6TFbHrIQaffKCjJjMx270YwnurrabN04Rbj+zci+z9Z0BMp/cpZB8CYeymNgMarjXVmrrj9MIOXazPq3pd1eigI=,iv:yIsyUmPNBr4YJMwYJQYziggfO6xLsbC0I09x2D5001Y=,tag:qgHLzRQ+YYPrm14yIbUaHw==,type:str]
    pgp:
    -   created_at: '2021-02-22T07:52:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hH4DTbnv4i6E7RESAgMEbAIUOSvVhLYCJ7ienx8Sf1FmuY2+CmdEwmVH3FpQcQYp
            vwh4ABFVQA4+aZE/8juM/6kLmt47zSKaDFIK7hevpDAbumB5VKVK2H4f/Wd9vRSQ
            KPvHq0MWbEWyURbIRMLN2oN7jojjVcCaGvhgJn/wtqzSXgE2tCCVq7PrdBC9a2rt
            pXNPlXEYZ56zNLIB4mmZ4XCgFsygR7eW3cuhOqna+qPbQI+gdxqZCNACI4ubduRs
            6Hr7L9Pz+F3LiqpCYAcGXBZ8K97W7AxzzmApICbx9z8=
            =tY+K
            -----END PGP MESSAGE-----
        fp: 3CAFE454CD9F1977A155A2E715A79E9BF178C897
    unencrypted_suffix: _unencrypted
    version: '1.18'
