secret_vars:
    AWS_IAM_ACCOUNT: ENC[AES256_GCM,data:GlR7VZhobOW9FlY=,iv:EovVhAwhuXnSeDQM8t8DPuSoiZtMTtzA4W0f+M/Yx/U=,tag:97LtFyAXUeMjJTENZ8iRjQ==,type:str]
    AWS_ACCESS_KEY: ENC[AES256_GCM,data:VrJLsF8KoGkOmOh4halFl9XggNs=,iv:wTRgC7MA3FzgscI4J7k4J1DR2XuY29SVXOyJFjcsMUs=,tag:iOrg8qRxI9+XH0RC9vNWyg==,type:str]
    AWS_SECRET_KEY: ENC[AES256_GCM,data:wt893uK/LKd/CfS/kAtV35BV0GMW0qZxc8izfxpgNMKXLwA8NqJW/Q==,iv:TzJvUHKO2XvkrcIQG7wQMIk9CwjGy7skkNjn4fVRMNA=,tag:mgLl15/6KAgsw81LIMuN0w==,type:str]
    API_KEY_NAME: ENC[AES256_GCM,data:Raa9LHQ+rA==,iv:nllGq1/88XSdIKr4wOZNF1YUZJzPzNzYfnDZ5QWA4gs=,tag:Vrp0krvfXTf+xhTc3Av1DA==,type:str]
    API_KEY: ENC[AES256_GCM,data:2FiKEddIr7HH493DmnQWAPm/wDCMAT6cY3F2BmcfBg==,iv:cjazSNMaFsSiBpMl/DKCQ1sbHXbTZrIy7EFWISSj4Ck=,tag:h6SJ4DYBeULeAuxxHaD+Xg==,type:str]
    ENVIRONMENT: ENC[AES256_GCM,data:c1a43GQBLgWroQ==,iv:IomyL+u9rKFwqiRYFBY3W+hZxtnOTjUNie2A/jQ7M10=,tag:ak4JW93i87NfypJ5R0y/Rw==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:pLczEbN0qG4oSz0E6bUtz7UkPzJOSlz0iND2LFemTFlgHeCm5xfiXPb61Cb3d7glVrDUwqDMSaH361NmVJ8hMBrN19kGIXC9,iv:Sr3eJr6z2os4qS0WrualE88GIXaVOkBpw18QUYS0vaI=,tag:tY45E32Uc/hsh2VYrZTslw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-27T08:25:28Z'
    mac: ENC[AES256_GCM,data:GgdeY3FVSMdq1Lhubp5etjSOQqGLSfJ27NGa/jmmaXcSq2QgnRGTFyZWpJMlA2skcFqoo5pkJgYrCK9UqiyeeOmWXsUpIcbBgrJ9czZ5PjDL7+VKaCHhfvOJzABDpaBlqg8Rzvd5tY3u2j3W5B/+y7W8ln12/KTZ2RGCKQslANc=,iv:lFZFcYHHg+9tzOlq81suMocPdJjg0i/AyxYMDIt1Y8I=,tag:B+RuAnYQTd3KqKLFllJ8Ow==,type:str]
    pgp:
    -   created_at: '2021-02-22T07:52:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hH4DTbnv4i6E7RESAgMEbAIUOSvVhLYCJ7ienx8Sf1FmuY2+CmdEwmVH3FpQcQYp
            vwh4ABFVQA4+aZE/8juM/6kLmt47zSKaDFIK7hevpDAbumB5VKVK2H4f/Wd9vRSQ
            KPvHq0MWbEWyURbIRMLN2oN7jojjVcCaGvhgJn/wtqzSXgE2tCCVq7PrdBC9a2rt
            pXNPlXEYZ56zNLIB4mmZ4XCgFsygR7eW3cuhOqna+qPbQI+gdxqZCNACI4ubduRs
            6Hr7L9Pz+F3LiqpCYAcGXBZ8K97W7AxzzmApICbx9z8=
            =tY+K
            -----END PGP MESSAGE-----
        fp: 3CAFE454CD9F1977A155A2E715A79E9BF178C897
    unencrypted_suffix: _unencrypted
    version: '1.18'
