ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: lead-scoring-api-dp-prod.elsanow.co
      paths:
        - /

resources:
  requests:
    cpu: 100m
    memory: 700M

image:
  repository: registry.gitlab.com/elsacorp/data-science/lead-scoring-backend
  tag: "production-latest"
  ## values: Always or IfNotPresent
  pullPolicy: Always
  pullSecret: gitlab-registry

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80